scrape_configs:
  - job_name: 'Movies Api job'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'DevFest Movies Api'
  - job_name: 'Movies Client job'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:8090']
        labels:
          application: 'DevFest Movies Client'
